services:
  db:
    image: postgres:16
    container_name: kviz-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kvizdb
      POSTGRES_USER: kviz
      POSTGRES_PASSWORD: kviz123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
